Updated GitHub Actions to include 4.14.0
Co-authored-by: Puneeth Chaganti <punchagan@muse-amuse.in>

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -10,7 +10,7 @@ on:
 
 # A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
-  build:
+  build-5-1:
     strategy:
       matrix:
         os:
@@ -74,7 +74,7 @@ jobs:
           export OPAM_DISABLE_SANDBOXING=true
           TAG='"run_in_ci"' make run_config_filtered.json
           sed -i 's/--cpu-list 5/--cpu-list 1/g' run_config_filtered.json
-          OPT_WAIT=0 USE_SYS_DUNE_HACK=1 RUN_CONFIG_JSON=run_config_filtered.json make ocaml-versions/5.1.0+trunk.bench  
+          OPT_WAIT=0 USE_SYS_DUNE_HACK=1 RUN_CONFIG_JSON=run_config_filtered.json make ocaml-versions/5.1.0+trunk.bench
           ls _results
           cat _results/*
           make json
@@ -108,3 +108,51 @@ jobs:
           cd ../parallel
           sudo chmod 777 .
           jupyter nbconvert --to html --execute parallel.ipynb
+
+  build-4-14:
+    strategy:
+      matrix:
+        os:
+          - ubuntu-latest
+        ocaml-compiler:
+          - 4.13.x
+
+    runs-on: ${{ matrix.os }}
+
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v3
+
+      - name: Use OCaml ${{ matrix.ocaml-compiler }}
+        uses: ocaml/setup-ocaml@v2
+        with:
+          ocaml-compiler: ${{ matrix.ocaml-compiler }}
+
+      - run: opam install . --deps-only --with-test
+
+      - name: 4.14.0+serial
+        run: |
+          sudo apt-get update && sudo apt-get -y install wget pkg-config libgmp-dev m4 libdw-dev jq python3-pip autoconf jo
+          pip3 install intervaltree
+          eval $(opam env)
+          export ITER=1
+          export OPAM_DISABLE_SANDBOXING=true
+          TAG='"run_in_ci"' make run_config_filtered.json
+          sed -i 's/--cpu-list 5/--cpu-list 1/g' run_config_filtered.json
+          OPT_WAIT=0 USE_SYS_DUNE_HACK=1 RUN_CONFIG_JSON=run_config_filtered.json make ocaml-versions/4.14.0.bench
+          ls _results
+          cat _results/*
+
+      - name: 4.14.0+parallel
+        run: |
+          sudo apt-get update && sudo apt-get -y install wget pkg-config libgmp-dev m4 libdw-dev jq python3-pip autoconf jo
+          pip3 install intervaltree
+          eval $(opam env)
+          export ITER=1
+          export OPAM_DISABLE_SANDBOXING=true
+          TAG='"run_in_ci"' make multicore_parallel_run_config_filtered.json
+          TAG='"macro_bench"' make multicore_parallel_run_config_filtered_filtered.json
+          sed -i 's/--cpu-list 5/--cpu-list 1/g' multicore_parallel_run_config_filtered.json
+          sed -i 's/--cpu-list 5/--cpu-list 1/g' multicore_parallel_run_config_filtered_filtered.json
+          make multicore_parallel_run_config_filtered_filtered_2domains.json
+          OPT_WAIT=0 USE_SYS_DUNE_HACK=1 BUILD_BENCH_TARGET=multibench_parallel RUN_CONFIG_JSON=multicore_parallel_run_config_filtered_filtered_2domains.json make ocaml-versions/4.14.0.bench || echo "Expected failure: Can't run parallel tests on 4.14.0"
